language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install: "cd httpd && pip install -r requirements.txt --use-mirrors"
# command to run tests (this runs from pwd of install command)
script: "nosetests"
